name: phpunit

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: composer update
      run: |
        composer update
    - name: test
      run: |
        mkdir -p build/logs
        XDEBUG_MODE=coverage ./vendor/bin/phpunit
    - name: coveralls
      run: |
        export COVERALLS_RUN_LOCALLY=1
        export COVERALLS_REPO_TOKEN=${{ secrets.coverallsToken }}
        composer require -W php-coveralls/php-coveralls
        php vendor/bin/php-coveralls -v
